plugins:
  - jekyll-feed
  - jekyll-sitemap

author: Ian Moore
summary: A Personal Site
lang: en
url: "https://wishfulwriting.github.io"
baseurl: ""

collections:
  recipes:
    output: true
    permalink: /recipes/:title

feed:
  posts_limit: 20
  